#!/usr/bin/env ruby
#
# PDFや画像をS3にアップロードしつつScrapboxに登録する
# Gyazoにも登録する
#

bucket = "masui.org"
project = "masui-files"

require 'digest/md5'
require 'shellwords'
require 'gyazo'

if `which open` != ""
  open = "open"
elsif `which xdg-open` != ""
  open = "xdg-open"
else
  STDERR.puts "open command not found"
  exit
end

if `which pbcopy` != ""
  pbcopy = "pbcopy"
elsif `which xsel` != ""
  pbcopy = "xsel --clipboard --input"
else
  STDERR.puts "copy command not found"
  exit
end

home = ENV['HOME']

token = ENV['GYAZO_TOKEN'] # .bash_profileに書いてある
gyazo = Gyazo::Client.new access_token: token

ARGV.each { |file|
  exit unless File.exist?(file)

  hash = Digest::MD5.new.update(File.read(file)).to_s

  if file =~ /^.*(\.\w+)$/ then
    ext = $1
  end
    
  dstfile = "s3://#{bucket}/#{hash[0]}/#{hash[1]}/#{hash}#{ext}"
  puts "s3cmd -c #{home}/.s3cfg put --acl-public #{Shellwords.escape(file)} #{dstfile} > /dev/null 2> /dev/null"
  system "s3cmd -c #{home}/.s3cfg put --acl-public #{Shellwords.escape(file)} #{dstfile} > /dev/null 2> /dev/null"

  urls = []
  if file =~ /\.pdf$/i
    # 画像にしてGyazoにアップロード
    system "convert -density 300 '#{file}[0]' /tmp/namecard.png"
    STDERR.puts "upload #{file} to Gyazo..."
    res = gyazo.upload imagefile: '/tmp/namecard.png'
    urls << res[:permalink_url]
    sleep 1
  elsif file =~ /\.(jpg|jpeg|gif|png)$/i
    STDERR.puts "upload #{file} to Gyazo..."
    res = gyazo.upload imagefile: file
    urls << res[:permalink_url]
    sleep 1
  end
    
  urls << "http://#{bucket}/#{hash}#{ext}"
  title = Time.now.strftime('%Y%m%d%H%M%S')

  scrapboxurl = "http://scrapbox.io/#{project}/#{title}?body=[#{urls.join(' ')}]%0d"

  # Scrapboxページ作成
  system "#{open} '#{scrapboxurl}'"
}
