#!/usr/bin/env ruby
#
# ファイルをS3にアップロードしつつScrapboxに登録する
# -n オプションをつけるとScrapboxに登録しない
#

bucket = "masui.org"
project = "masui-files"

require 'digest/md5'
require 'shellwords'
require 'gyazo'

if `which open` != ""
  open = "open"
elsif `which xdg-open` != ""
  open = "xdg-open"
else
  STDERR.puts "open command not found"
  exit
end

if `which pbcopy` != ""
  pbcopy = "pbcopy"
elsif `which xsel` != ""
  pbcopy = "xsel --clipboard --input"
else
  STDERR.puts "copy command not found"
  exit
end

home = ENV['HOME']

token = ENV['GYAZO_TOKEN'] # .bash_profileに書いてある
gyazo = Gyazo::Client.new access_token: token

ARGV.each { |file|
  exit unless File.exist?(file)

  affil = ''
  if file =~ /^(.*)@(.*)(\.\w+)$/ then
    name = $1
    affil = $2
    ext = $3
  elsif file =~ /^(.*)(\.\w+)$/ then
    name = $1
    ext = $2
  else
    next
  end

  hash = Digest::MD5.new.update(File.read(file)).to_s

  dstfile = "s3://#{bucket}/#{hash[0]}/#{hash[1]}/#{hash}#{ext}"
  puts "s3cmd -c #{home}/.s3cfg put --acl-public #{Shellwords.escape(file)} #{dstfile} > /dev/null 2> /dev/null"
  system "s3cmd -c #{home}/.s3cfg put --acl-public #{Shellwords.escape(file)} #{dstfile} > /dev/null 2> /dev/null"

  # 画像にしてGyazoにアップロード
  system "convert -density 300 '#{file}[0]' /tmp/namecard.png"
  STDERR.puts "upload #{file} to Gyazo..."
  res = gyazo.upload imagefile: '/tmp/namecard.png'
  gyazourl = res[:permalink_url]
  sleep 1

  url = "http://#{bucket}/#{hash}#{ext}"

  if affil == ''
    title = name
    scrapboxurl = "http://scrapbox.io/#{project}/#{title}?body=[#{gyazourl} #{url}]%0d%0d%23#{name} %23名刺"
  else
    title = "#{name}@#{affil}"
    scrapboxurl = "http://scrapbox.io/#{project}/#{title}?body=[#{gyazourl} #{url}]%0d%0d%23#{name} %23#{affil} %23名刺"
  end
  # Scrapboxページ作成
  system "#{open} '#{scrapboxurl}'"
}
