#!/usr/bin/env ruby
#
# ファイルをS3にアップロード
#

bucket = "masui.org"
project = "masui-files"

require 'digest/md5'
require 'shellwords'

if `which open` != ""
  open = "open"
elsif `which xdg-open` != ""
  open = "xdg-open"
else
  STDERR.puts "open command not found"
  exit
end

if `which pbcopy` != ""
  pbcopy = "pbcopy"
elsif `which xsel` != ""
  pbcopy = "xsel --clipboard --input"
else
  STDERR.puts "copy command not found"
  exit
end

file = ARGV.shift
exit unless file
exit unless File.exist?(file)

home = ENV['HOME']

ext = ''
if file =~ /^(.*)(\.\w+)$/ then
  ext = $2
end

hash = Digest::MD5.new.update(File.read(file)).to_s

dstfile = "s3://#{bucket}/#{hash[0]}/#{hash[1]}/#{hash}#{ext}"
puts "s3cmd -c #{home}/.s3cfg put --acl-public #{Shellwords.escape(file)} #{dstfile} > /dev/null 2> /dev/null"
system "s3cmd -c #{home}/.s3cfg put --acl-public #{Shellwords.escape(file)} #{dstfile} > /dev/null 2> /dev/null"
puts "http://#{bucket}.s3.amazonaws.com/#{hash[0]}/#{hash[1]}/#{hash}#{ext}"
system "echo http://#{bucket}.s3.amazonaws.com/#{hash[0]}/#{hash[1]}/#{hash}#{ext} | #{pbcopy}"
